In [1]:
import pandas as pd
import pyodbc
from sqlalchemy import create_engine
from urllib.parse import quote_plus
from db import build_conn_str, get_connection

In [2]:
engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={quote_plus(build_conn_str())}"
)

In [3]:
df = pd.read_csv("articles.csv")
df.head()

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,108775051,108775,Strap top (1),253,Vest top,Garment Upper body,1010017,Stripe,11,Off White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."

In [4]:
products = df.drop(
    columns=[
        "product_type_name",
        "graphical_appearance_name",
        "colour_group_name",
        "perceived_colour_value_name",
        "perceived_colour_master_name",
        "department_name",
        "index_name",
        "index_group_name",
        "section_name",
        "garment_group_name",
        "product_group_name"
    ]
)

products

,article_id,product_code,prod_name,product_type_no,graphical_appearance_no,colour_group_code,perceived_colour_value_id,perceived_colour_master_id,department_no,index_code,index_group_no,section_no,garment_group_no,detail_desc
0,108775015,108775,Strap top,253,1010016,9,4,5,1676,A,1,16,1002,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,1010016,10,3,9,1676,A,1,16,1002,Jersey top with narrow shoulder straps.
2,108775051,108775,Strap top (1),253,1010017,11,1,9,1676,A,1,16,1002,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,1010016,9,4,5,1339,B,1,61,1017,"Microfibre T-shirt bra with underwired, moulde..."
4,110065002,110065,OP T-shirt (Idro),306,1010016,10,3,9,1339,B,1,61,1017,"Microfibre T-shirt bra with underwired, moulde..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105537,953450001,953450,5pk regular Placement1,302,1010014,9,4,5,7188,F,3,26,1021,Socks in a fine-knit cotton blend with a small...
105538,953763001,953763,SPORT Malaga tank,253,1010016,9,4,5,1919,A,1,2,1005,Loose-fitting sports vest top in ribbed fast-d...
105539,956217002,956217,Cartwheel dress,265,1010016,9,4,5,1641,A,1,18,1005,"Short, A-line dress in jersey with a round nec..."
105540,957375001,957375,CLAIRE HAIR CLAW,72,1010016,9,4,5,3946,D,2,52,1019,Large plastic hair claw.
105541,959461001,959461,Lounge dress,265,1010016,11,1,9,1641,A,1,18,1005,Calf-length dress in ribbed jersey made from a...

In [5]:
product_types = (
    df[["product_type_no", "product_type_name"]]
    .drop_duplicates()
    .sort_values("product_type_no")
)
product_types

       product_type_no product_type_name
64                  -1           Unknown
2729                49     Sleeping sack
160                 57          Swimsuit
135                 59   Swimwear bottom
3548                60      Swimwear top
...                ...               ...
78893              525          Keychain
92855              529       Mobile case
36                 532          Umbrella
97586              761        Marker pen
92078              762       Zipper head

[132 rows x 2 columns]

In [6]:
product_groups = (
    df[["product_group_name"]]
    .drop_duplicates()
    .sort_values("product_group_name")
)
product_groups

          product_group_name
28               Accessories
31745                   Bags
6426                Cosmetic
95767                    Fun
62949              Furniture
204        Garment Full body
8         Garment Lower body
0         Garment Upper body
84758  Garment and Shoe care
26032       Interior textile
36                     Items
37                 Nightwear
124                    Shoes
6             Socks & Tights
97586             Stationery
134                 Swimwear
3                  Underwear
107      Underwear/nightwear
64                   Unknown

In [7]:
appearances = (
    df[["graphical_appearance_no", "graphical_appearance_name"]]
    .drop_duplicates()
    .sort_values("graphical_appearance_no")
)
appearances

       graphical_appearance_no graphical_appearance_name
1099                        -1                   Unknown
11                     1010001          All over pattern
37                     1010002            Application/3D
1835                   1010003                    Argyle
242                    1010004                     Check
78                     1010005           Colour blocking
89                     1010006                       Dot
615                    1010007                Embroidery
309                    1010008               Front print
351                    1010009       Glittering/Metallic
16                     1010010                   Melange
30                     1010011                  Metallic
357                    1010012       Mixed solid/pattern
459                    1010013             Other pattern
393                    1010014           Placement print
5491                   1010015                    Sequin
0                      1010016                     Solid
2                      1010017                    Stripe
183                    1010018                 Treatment
29                     1010019               Transparent
176                    1010020                  Contrast
684                    1010021                      Lace
934                    1010022                  Jacquard
69                     1010023                     Denim
251                    1010024                  Chambray
2079                   1010025                      Slub
133                    1010026           Other structure
463                    1010027                      Neps
5035                   1010028                      Mesh
66362                  1010029                  Hologram

In [8]:
colors = (
    df[
        [
            "colour_group_code",
            "colour_group_name",
        ]
    ]
    .drop_duplicates()
    .sort_values("colour_group_code")
)
colors

color_value = (
    df[
        [
            "perceived_colour_value_id",
            "perceived_colour_value_name",
        ]
    ]
    .drop_duplicates()
    .sort_values("perceived_colour_value_id")
)
color_value

color_master = (
    df[
        [
            "perceived_colour_master_id",
            "perceived_colour_master_name",
        ]
    ]
    .drop_duplicates()
    .sort_values("perceived_colour_master_id")
)
color_master

       perceived_colour_master_id perceived_colour_master_name
1095                           -1                      Unknown
29                              1                         Mole
12                              2                         Blue
30                              3                       Orange
20                              4                         Pink
0                               5                        Black
22                              6                 Lilac Purple
90                              7                    Turquoise
94                              8                       Yellow
1                               9                        White
34968                          10              Yellowish Green
5                              11                        Beige
11                             12                         Grey
61                             13                        Brown
257                            14                    undefined
31                             15                        Metal
35980                          16                 Bluish Green
25                             18                          Red
166                            19                        Green
100                            20                  Khaki green

In [9]:
departments = (
    df[["department_no", "department_name"]]
    .drop_duplicates()
    .sort_values("department_no")
)
departments

       department_no     department_name
2178            1201             Outwear
7179            1202             Jackets
5817            1212                Suit
6186            1222         Suit jacket
10344           1241   Outwear & Blazers
...              ...                 ...
11194           9020  Special Collection
3117            9984            Swimwear
381             9985         Accessories
1058            9986   Small Accessories
8562            9989          Loungewear

[299 rows x 2 columns]

In [10]:
sections = (
    df[["section_no", "section_name"]]
    .drop_duplicates()
    .sort_values("section_no")
)
sections

       section_no                    section_name
814             2                            H&M+
38956           4                    Ladies Other
3182            5                Ladies H&M Sport
2711            6                   Womens Casual
23              8                            Mama
1448           11                Womens Tailoring
4417           14                  Womens Premium
457            15      Womens Everyday Collection
0              16          Womens Everyday Basics
43598          17                    Ladies Other
1291           18                    Womens Trend
2178           19                  Womens Jackets
921            20              Contemporary Smart
322            21             Contemporary Casual
40             22                   Men H&M Sport
442            23           Men Suits & Tailoring
5961           24                     Men Project
381            25                 Men Accessories
16             26                   Men Underwear
571            27                       Men Shoes
9286           28                     Men Edition
1660           29                       Men Other
2444           30                     Men Other 2
99             31                  Mens Outerwear
3768           40                       Baby Girl
2494           41                        Baby Boy
3530           42               Kids & Baby Shoes
3128           43  Kids Accessories, Swimwear & D
11             44   Baby Essentials & Complements
1367           45                  Kids Outerwear
69             46                        Kids Boy
760            47                       Young Boy
28047          48            Kids Local Relevance
5669           49                     Kids Sports
1524           50                Divided Projects
78             51                  Divided Basics
124            52             Divided Accessories
902            53              Divided Collection
242            55             Contemporary Street
1627           56                       Denim Men
906            57                    Ladies Denim
204            58                Divided Selected
134            60      Womens Swimwear, beachwear
3              61                 Womens Lingerie
6              62  Womens Nightwear, Socks & Tigh
1425           64                    Womens Shoes
121            65          Womens Big accessories
28             66        Womens Small accessories
15205          70               Divided Asia keys
17072          71                      EQ Divided
216            72         Boys Underwear & Basics
3939           76                       Kids Girl
1400           77                      Young Girl
81             79        Girls Underwear & Basics
4124           80       Divided Complements Other
4753           82             Special Collections
11195          97                  Collaborations

In [11]:
garment_groups = (
    df[["garment_group_no", "garment_group_name"]]
    .drop_duplicates()
    .sort_values("garment_group_no")
)
garment_groups

      garment_group_no             garment_group_name
2444              1001                        Unknown
0                 1002                   Jersey Basic
204               1003                       Knitwear
23                1005                   Jersey Fancy
3338              1006  Woven/Jersey/Knitted mix Baby
99                1007                        Outdoor
442               1008                        Dressed
274               1009                       Trousers
2046              1010                        Blouses
242               1011                         Shirts
1228              1012                         Skirts
496               1013                 Dresses Ladies
3622              1014           Dresses/Skirts girls
69                1016                 Trousers Denim
3                 1017              Under-, Nightwear
134               1018                       Swimwear
28                1019                    Accessories
124               1020                          Shoes
6                 1021               Socks and Tights
1660              1023                 Special Offers
493               1025                         Shorts

In [12]:
indices = (
    df[
        [
            "index_code",
            "index_name"
        ]
    ]
    .drop_duplicates()
    .sort_values("index_code")
)

In [13]:
index_group = (
    df[
        [
            "index_group_no",
            "index_group_name"
        ]
    ]
    .drop_duplicates()
    .sort_values("index_group_no")
)

In [14]:

products.to_sql(
    "Products",
    con=engine,
    if_exists="replace",
    index=False
)

50

In [15]:
'''
product_types.to_sql("ProductTypes", engine, if_exists="replace", index=False)
product_groups.to_sql("ProductGroups", engine, if_exists="replace", index=False)
appearances.to_sql("Appearances", engine, if_exists="replace", index=False)
departments.to_sql("Departments", engine, if_exists="replace", index=False)
sections.to_sql("Sections", engine, if_exists="replace", index=False)
garment_groups.to_sql("GarmentGroups", engine, if_exists="replace", index=False)
'''

'\nproduct_types.to_sql("ProductTypes", engine, if_exists="replace", index=False)\nproduct_groups.to_sql("ProductGroups", engine, if_exists="replace", index=False)\nappearances.to_sql("Appearances", engine, if_exists="replace", index=False)\ndepartments.to_sql("Departments", engine, if_exists="replace", index=False)\nsections.to_sql("Sections", engine, if_exists="replace", index=False)\ngarment_groups.to_sql("GarmentGroups", engine, if_exists="replace", index=False)\n'

In [16]:
'''
colors.to_sql("Colors", engine, if_exists="replace", index=False)
color_value.to_sql("ColorValues", engine, if_exists="replace", index=False)
color_master.to_sql("ColorMasters", engine, if_exists="replace", index=False)
'''

'\ncolors.to_sql("Colors", engine, if_exists="replace", index=False)\ncolor_value.to_sql("ColorValues", engine, if_exists="replace", index=False)\ncolor_master.to_sql("ColorMasters", engine, if_exists="replace", index=False)\n'

In [17]:
'''
index_group.to_sql("IndexGroup", engine, if_exists="replace", index=False)
'''

'\nindex_group.to_sql("IndexGroup", engine, if_exists="replace", index=False)\n'

In [18]:
'''
indices.to_sql("Indices", engine, if_exists="replace", index=False)
'''

'\nindices.to_sql("Indices", engine, if_exists="replace", index=False)\n'

In [19]:
df.columns.tolist()

['article_id',
 'product_code',
 'prod_name',
 'product_type_no',
 'product_type_name',
 'product_group_name',
 'graphical_appearance_no',
 'graphical_appearance_name',
 'colour_group_code',
 'colour_group_name',
 'perceived_colour_value_id',
 'perceived_colour_value_name',
 'perceived_colour_master_id',
 'perceived_colour_master_name',
 'department_no',
 'department_name',
 'index_code',
 'index_name',
 'index_group_no',
 'index_group_name',
 'section_no',
 'section_name',
 'garment_group_no',
 'garment_group_name',
 'detail_desc']